### ISSUE TITLE
could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)

### ISSUE THREAD

**Issue by tinntvs** [Baune8D/packer-win10-basebox#2]
![image](https://user-images.githubusercontent.com/87159604/234225807-a223286a-6898-466f-9d9a-aec57314280a.png)

What are the relate apps I need to install?

Please help me, Thank you!

**Comment by Baune8D** [comment]
It tells you in the output:

![image](https://user-images.githubusercontent.com/30204280/234265118-4447778e-7411-4476-8935-7757d9c5d8ff.png)

You need to have 1 of these tools in your PATH.

I usually use `oscdimg` which can be installed through the Windows ADK: https://learn.microsoft.com/en-us/windows-hardware/get-started/adk-install

**Comment by Baune8D** [comment]
I assume you figured it out since there has been no response 👍
