### ISSUE TITLE
Creating windows 11 hyper-v image stuck at last provisisoning setup (setting winrm service startup)

### ISSUE THREAD

**Issue by junaid-ebrahim** [Baune8D/packer-win10-basebox#3]
Hi 

My packer (version 1.8.7) hangs on the following build attempt

`packer build --force --only hyperv-iso -var "cpus=8" -var "memory=8192" -var "disk_size=80000" -var "iso_url=./Win11_22H2_English_x64v1.iso" .\windows_11.json`

Standard packer install except I had to install this to fix the error "Error getting host adapter ip address: No ip address"
`packer plugins install github.com/hashicorp/hyperv "=1.1.0"`

**The workaround is to remove the last step from windows_11.json , see below is the code I need to remove**
`    {
      "execute_command": "{{ .Vars }} cmd /c \"{{ .Path }}\"",
      "remote_path": "/tmp/script.bat",
      "scripts": [
        "./scripts/set-winrm-automatic.ps1"
      ],
      "type": "powershell"
    }
`

Running Packer with the following configuration.

  Host OS: Windows 11
  Guest OS: Windows 11
  Type: hyperv-iso
  Switch : Default Switch

Not sure the last step is required as the WinRM service is "Automatic (delayed start)" so changing this to "Automatic" does not seem to be required.

See the command line text of an execution attempt showing the error.

****************** start
C:\Users\junaid\Documents\Code\packer-windows-desktop>packer build --only hyperv-iso -var "cpus=8" -var "memory=8192" -var "disk_size=80000" -var "iso_url=./iso/Win11_22H2_English_x64v1.iso" .\windows_11.json                                Warning: Warning when preparing build: "hyperv-iso"

A checksum of 'none' was specified. Since ISO files are so big,
a checksum is highly recommended.

Warning: Warning when preparing build: "hyperv-iso"

Hyper-V might fail to create a VM if there is not enough free memory in the
system.

hyperv-iso: output will be in this color.

==> hyperv-iso: Creating build directory...
==> hyperv-iso: Retrieving ISO
==> hyperv-iso: Trying ./iso/Win11_22H2_English_x64v1.iso
==> hyperv-iso: Trying ./iso/Win11_22H2_English_x64v1.iso
==> hyperv-iso: ./iso/Win11_22H2_English_x64v1.iso => C:/Users/junaid/Documents/Code/packer-windows-desktop/iso/Win11_22H2_English_x64v1.iso
==> hyperv-iso: Creating switch 'Default Switch' if required...
==> hyperv-iso:     switch 'Default Switch' already exists. Will not delete on cleanup...
==> hyperv-iso: Creating virtual machine...
==> hyperv-iso: Enabling Integration Service...                                                                         ==> hyperv-iso: Setting boot drive to os dvd drive C:/Users/junaid/Documents/Code/packer-windows-desktop/iso/Win11_22H2_English_x64v1.iso ...                                                                                                   ==> hyperv-iso: Mounting os dvd drive C:/Users/junaid/Documents/Code/packer-windows-desktop/iso/Win11_22H2_English_x64v1.iso ...                                                                                                                ==> hyperv-iso: Skipping mounting Integration Services Setup Disk...
==> hyperv-iso: Creating CD disk...
    hyperv-iso: OSCDIMG 2.56 CD-ROM and DVD-ROM Premastering Utility
    hyperv-iso: Copyright (C) Microsoft, 1993-2012. All rights reserved.
    hyperv-iso: Licensed only for producing Microsoft authorized content.
    hyperv-iso: Scanning source tree
    hyperv-iso: Scanning source tree complete (7 files in 1 directories)
    hyperv-iso: Computing directory information complete
    hyperv-iso: Image file is 83968 bytes (before optimization)
    hyperv-iso: Writing 7 files in 1 directories to C:\Users\junaid\AppData\Local\Temp\packer2448409483.iso
    hyperv-iso: Storage optimization saved 0 files, 0 bytes (0% of image)
    hyperv-iso: 100% complete
    hyperv-iso: After optimization, image file is 83968 bytes
    hyperv-iso: Done.
    hyperv-iso: Done copying paths from CD_dirs
==> hyperv-iso: Mounting secondary DVD images...
==> hyperv-iso: Mounting secondary dvd drive C:\Users\junaid\AppData\Local\Temp\packer2448409483.iso ...
==> hyperv-iso: Configuring vlan...
==> hyperv-iso: Determine Host IP for HyperV machine...
==> hyperv-iso: Host IP for the HyperV machine: 172.21.112.1
==> hyperv-iso: Attempting to connect with vmconnect...
==> hyperv-iso: Starting the virtual machine...
==> hyperv-iso: Typing the boot command...
==> hyperv-iso: Waiting for WinRM to become available...
    hyperv-iso: WinRM connected.
==> hyperv-iso: Connected to WinRM!
==> hyperv-iso: Provisioning with Powershell...
==> hyperv-iso: Provisioning with powershell script: ./scripts/enable-rdp.ps1
    hyperv-iso: Enabling RDP
==> hyperv-iso: Provisioning with powershell script: ./scripts/vm-guest-tools.ps1
==> hyperv-iso: Restarting Machine
==> hyperv-iso: Waiting for machine to restart...
==> hyperv-iso: A system shutdown is in progress.(1115)
    hyperv-iso: vagrant-win11 restarted.
==> hyperv-iso: Machine successfully restarted, moving on
==> hyperv-iso: Provisioning with Powershell...
==> hyperv-iso: Provisioning with powershell script: ./scripts/set-winrm-automatic.ps1
Cancelling build after receiving interrupt
==> hyperv-iso: Disconnecting from vmconnect...
==> hyperv-iso: Clean up secondary dvd drives...
==> hyperv-iso: Clean up os dvd drive...
==> hyperv-iso: Unregistering and deleting virtual machine...
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting build directory...
Build 'hyperv-iso' errored after 1 hour 3 minutes: Build was cancelled.

==> Wait completed after 1 hour 3 minutes
Cleanly cancelled builds after being interrupted.
****************** end

Regards
Junaid

**Comment by Baune8D** [comment]
Hi there and thanks for the issue.

You are correct. When i converted the `set-winrm-automatic` script to powershell some time ago, i forgot to fix `execute_command` and `remote_path` for that section so it gets incorrectly executed. But as you say, it is irrelevant to run anyways. It is a leftover from StefanScherers original repository, but since this repository is highly simplified, it is not needed anymore so i will remove it.

About the Packer plugin: This seems to be something new that Packer has introduced. For now i will write into the README that you need to install the plugins for your provider yourself. But i will look into converting the templates to HCL2 a little later so they will be downloaded automatically.

I am currently cooking up some minor other changes and releasing new builds of images for all providers. I will address these issues when in the update when i am done 👍

**Comment by Baune8D** [comment]
Fixes merged to main
